User.destroy_all
Perfume.destroy_all
Result.destroy_all
Note.destroy_all
Review.destroy_all
Favorite.destroy_all
Magasin.destroy_all
Order.destroy_all

puts "Creating users..."
users = User.create!([
  { name: 'Alice', surname: 'Dupont', address: '12 Rue de la Paix, Paris', email: 'alice.dupont@example.com', password: 'password', latitude: 48.868, longitude: 2.328 },
  { name: 'Solène', surname: 'Baudic', address: '34 Avenue des Champs-Élysées, Paris', email: 'solene.baudic@gmail.com', password: '123456', latitude: 48.869, longitude: 2.307 },
  { name: 'Loic', surname: 'Carpentier', address: '34 Avenue des Champs-Élysées, Paris', email: 'carpentier.loic19@gmail.com', password: '123456', latitude: 48.869, longitude: 2.307 },
  { name: 'Jenna-Claudia', surname: 'Andria', address: 'Pantin', email: 'jennaandria@gmail.com', password: '123456', latitude: 48.894, longitude: 2.412 }
])
puts "finished creating users"
puts "Creating perfumes..."
perfumes = Perfume.create!([
  # { name: 'Shalimar', description: 'Une fragrance orientale iconique avec des notes de bergamote, iris et vanille.', brand: 'Guerlain', price: 120.0, photo: 'shalimar.jpg', intensity: 5 },
  # { name: 'Mon Guerlain', description: 'Un parfum oriental frais avec des notes de lavande, jasmin Sambac et bois de santal.', brand: 'Guerlain', price: 110.0, photo: 'mon_guerlain.jpg', intensity: 3 },
  # { name: 'Aqua Allegoria Mandarine Basilic', description: 'Un parfum frais et pétillant avec des notes de mandarine et basilic.', brand: 'Guerlain', price: 85.0, photo: 'aqua_allegoria_mandarine_basilic.jpg', intensity: 2 },
  # { name: 'L\'Homme Idéal', description: 'Un parfum masculin avec des notes d\'amande, cuir et vanille.', brand: 'Guerlain', price: 95.0, photo: 'lhomme_ideal.jpg', intensity: 4 },Un bouquet d’herbes et aromates
  {name: 'L’homme idéal le parfum', description: 'Avec son caractère emprunté à l’amaretto, liqueur italienne à la saveur typique d’amande amère, L’Homme Idéal Le Parfum renforce la sensualité subtilement gourmande du sillage originel. Sa senteur captivante se déploie sur une note de cœur cuirée plus profonde et mystérieuse que jamais : facettée par les accents boisés et mystérieux des notes de patchouli, elle dessine une séduction captivante et intense. Enveloppé dans un cocon de notes musquées, l’ensemble se prolongitudee dans un sillage sensuel et irrésistible.', brand: 'Guerlain', price: 150, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw200bc326/primary_packshot_3/2024/FRAGRANCE/L__HOMME_IDEAL_-_EDP_100ml-263403.png?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'L’homme ideal Extrême', description: 'Pour cette nouvelle interprétation de l’Homme Idéal, Thierry Wasser, Parfumeur de la maison Guerlain, a choisi d’explorer de nouvelles facettes de l’amande, la signature olfactive de L’Homme Idéal. Au cœur de la composition, elle se montre ambrée et boisée à l’extrême, soutenue par l’audace des épices et le charisme chaleureux du tabac. L’amande, sceau olfactif de l’Homme Idéal, s’accompagne en tête de l’effervescence de la bergamote mêlée au poivre rose. En cœur, la cannelle et des notes prune viennent escorter l’héliotrope, note florale aux accents amandés élégants. Enfin, le charme d’une note de fond boisée patchouli et cèdre se pare de tabac et d’une intense note cuir.', brand: 'Guerlain', price: 125, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw2d6d8e4a/primary_packshot_3/2022/Fragrance/Men_Repack/G030434_3346470304345_L’HOMME-20-IDEAL-EXTREME-EDP-VAPO-100ML_1.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'L’homme ideal L’intense', description: 'L’intensité est le point d’orgue de cette nouvelle interprétation de l’Homme Idéal. Dès la tête, le piment embrase de sa facette d’épices chaudes, une fève Tonka vive et envoûtante. En fond, les notes fumées associées à la mythique teinture de vanille viennent signer une fragrance résolument intrigante.', brand: 'Guerlain', price: 125, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw7a39c039/primary_packshot_3/2023/Fragrances/MASCULINS/L_HOMME_IDEAL_INTENSE_EDP_100ml-226615.png', intensity: 2, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un cocktail intense et puissant'},
  {name: 'L’homme ideal Eau de Parfum', description: 'Une amande captivante, la séduction d’une teinture de vanille chaleureuse et le mystère d’une note cuir. Guerlain est l’un des derniers parfumeurs à utiliser la technique de la teinture de vanille. Elle est réalisée à l’usine d’Orphin de manière artisanale et consiste à découper les gousses en petits morceaux et les plongitudeer dans l’alcool jusqu’à ce qu’il prenne une belle couleur ambrée chaleureuse.', brand: 'Guerlain', price: 125, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw484d31c7/primary_packshot_3/2022/Fragrance/Men_Repack/G030312_3346470303126_L’HOMME-IDEAL-16-EDP-VAPO-100ML_1.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un bouquet de fleurs'},
  {name: 'Eau de Cologne du Coq', description: 'L’Eau de Cologne du Coq illustre la fraîcheur à la fois délicate et acidulée d’un matin de printemps. Légère comme un zéphyr, elle est composée de senteurs hespéridées comme le citron, la bergamote ou l’orange mais aussi de notes aromatiques comme le romarin et la lavande.', brand: 'Guerlain', price: 114, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwd09eb117/primary_packshot_3/2022/Fragrance/Colognes/G021746_3346470217461_EAU-90-COQ-EDC-VAPO-100ML_1.png?sw=900&sh=900', intensity: 1, genre: 'Pour homme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'EAu de cologne Imperial', description: 'La célèbre Eau de Cologne Impériale s’harmonise autour d’accords fleuris et raffinés. Ses notes fraîches hespéridées de citron et de bergamote flirtent avec le petit grain, tandis que la magie florale du néroli vient adoucir ce bouquet d’agrumes.', brand: 'Guerlain', price: 114, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw61e2baa7/primary_packshot_3/2022/Fragrance/Colognes/G021766_3346470217669_EAU-90-IMP-EDC-VAPO-100ML_1.png?sw=900&sh=900', intensity: 1, genre: 'Pour homme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Cologne du Parfumeur', description: 'La Cologne du Parfumeur sublime une fleur d’oranger d’une douceur extrême avec une facette verte et croquante. Elle nous dévoile ensuite des notes musquées qui rendent la composition originale et intimiste.', brand: 'Guerlain', price: 114, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwc0864bc0/primary_packshot_3/2022/Fragrance/Colognes/G017053_3346470170537_COLOGNE-PARF-10-EDC-VAPO-100ML_1.png?sw=900&sh=900', intensity: 3, genre: 'Pour homme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Encens Mythique', description: 'Fascinant et énigmatique, l’encens a inspiré Thierry Wasser, Maître-Parfumeur Guerlain, pour cette création ambrée, comme une essence brûlante. La fragrance, empreinte d’un encens aérien, est relevée par la rose et sublimée par l’ambre gris qui apporte douceur sans mesure et profondeur exceptionnelle.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw7539e660/primary_packshot_3/2022/Fragrance/Absolus_Dorient/G013630_3346470136304_ENC_MYTH-22-EDP-VAPO-125ML.png?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un souvenir de vacances épicé'},
  {name: 'Patchouli Ardent', description: 'Avec Patchouli Ardent, Thierry Wasser, Maître-Parfumeur Guerlain, propose une interprétation inédite du patchouli. Matière première habituellement boisée, sombre et mystérieuse, il la sublime de manière étonnamment vibrante et lumineuse. Il associe à l’élégance de la rose, un accord majestueux de cuir et de muscs pour offrir un voyage sensoriel unique.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw8f18d7eb/primary_packshot_3/2022/Fragrance/Absolus_Dorient/G014018_3346470140189_PATCHOULI-22-EDP-VAPO-125ML.png?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un fruit frais ou sucré'},
  {name: 'Cuir Intense', description: 'Matière première d’exception, le cuir fait partie intégrante d’une tradition millénaire en Orient. Thierry Wasser, Maître-Parfumeur Guerlain, lui rend hommage dans Cuir Intense, qui met en avant sa force, sa souplesse et sa sensualité. Le parfumeur s’appuie sur les contrastes entre la puissance des notes cuirées boisées et la lumière de la fleur d’Osmanthus aux facettes fruitées abricotées.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw053e041f/primary_packshot_3/2022/Fragrance/Absolus_Dorient/G013678_3346470136786_CUIR_INTENSE-22-EDP-VAPO-125ML.png?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Des embruns rafraichissants'},
  {name: 'Habit rouge', description: 'Premier parfum masculin ambré, Habit Rouge puise son inspiration dans l’univers de l’équitation cher à son créateur Jean-Paul Guerlain. Lancé en 1965, son sillage boisé et épicé, enveloppé par la rondeur de la vanille, devient un emblème olfactif de l’élégance à la française. Inspiré par le caractère à la fois intense et chaleureux d’un bourbon, Habit Rouge Le Parfum évoque la tonalité d’un accord de rhum. Une entrée en matière idéale pour la teinture de vanille réalisée selon un procédé maison de Guerlain. Accompagnée de patchouli, cette teinture de vanille offre à la signature d’Habit Rouge une profondeur inédite.', brand: 'Guerlain', price: 150, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw6426c684/primary_packshot_3/2024/FRAGRANCE/LES-MASCULINS-24_SECONDARY-VISUAL_PDP_KV_HR.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un bouquet de fleurs'},
  {name: 'Vetiver', description: 'Travaillé dans l’esprit d’un gin, Vétiver Le Parfum s’ouvre par une note fusante de baies de genièvre à la senteur aromatique et légèrement amère. Un départ tonique et énergique, qui exacerbe les facettes les plus fraîches d’une essence de vétiver exceptionnelle. Cet ingrédient noble, obtenu par distillatitudeion des racines de la plante, révèle toute la profondeur de ses nuances boisées. Il se mêle à des notes fumées envoûtantes et à l’addictive fève tonka si chère à Guerlain. Un sillage à la fois lumineux et terrestre, équilibre sublime de puissance et d’élégance.', brand: 'Guerlain', price: 150, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw5aaf3cea/primary_packshot_3/2024/FRAGRANCE/LES-MASCULINS-24_SECONDARY-VISUAL_PDP_KV_VETIVER.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'L’instant homme', description: 'L’Instant de Guerlain pour Homme magnifie un moment unique : l’instant où l’homme prend l’initiative, celui après lequel tout sera différent. C’est un parfum boisé, éclatitudeant, séducteur. Travaillé en contrastes, il crée la surprise.', brand: 'Guerlain', price: 125, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw1194313b/primary_packshot_3/2022/Fragrance/Men_Repack/G030489_3346470304895_L’INSTANT%20HOMME%2022%20EDP%20VAPO%20100ML.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'Santal royal', description: 'Un santal envoûtant, teinté de mystère, mis en majesté dans cette nouvelle fragrance boisée et ambrée. Un jeu de contrastes subtils entre les notes sombres du cuir, de l’accord oud et la luminosité des notes florales du jasmin et de la rose.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw212bb851/Secondary_visuals_2/2022/Fragrance/Absolus_Dorient/AO-HAIR-MIST_SQUARE-IMAGE_PDP_PACK-SOLO.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Epices exquises', description: 'Épices Exquises est l’évocation d’un voyage sensoriel. Thierry Wasser a capturé l’essence d’un parfum irrésistiblement ambré: les effluves épicées du café à la cardamome. À la manière des volutes chaudes et grisantes de ce café, Epices Exquises mêle un fond chaud, corsé et sensuel, teinté de poivre noir et de notes boisées de oud, de patchouli et de santal, à des facettes rafraîchissantes subtilement surdosées de cardamome, de notes de baies roses et d’angélique verte et fraîche.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw4613a8aa/primary_packshot_3/2022/Fragrance/Absolus_Dorient/Key_Visuals/AO_SECONDARY-VISUAL_PRODUCT-PAGE_01.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour homme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un souvenir de vacances épicé'},
  {name: 'Feve gourmande', description: 'Entre la gourmandise du chocolatitude, le vertige des notes de rhum et le raffinement de la rose, la note cacao bascule dans une réalité alternative.', brand: 'Guerlain', price: 465, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw686bf9d3/primary_packshot_3/2023/Fragrances/A&M/AM-FEVE_SECONDARY-VISUAL_PDP_EDP_02_FACE-100ML.jpg?sw=900&sh=900', intensity: 4, genre: 'Mixte', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un dessert très gourmand'},
  {name: 'Oud khol', description: 'Célébration du noir en parfum, Oud Khôl révèle les plus belles facettes du bois de oud noir. Comme ce khôl qui purifie l’œil autant qu’il intensifie le regard, le bois de oud permet au Maître-Parfumeur Guerlain Thierry Wasser d’atteindre le noir absolu.', brand: 'Guerlain', price: 465, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw179b4af1/primary_packshot_3/2022/Fragrance/A&M/Parfums/AM-OUDS_PRIMARY-VISUAL_PDP_KHOL.jpg?sw=900&sh=900', intensity: 5, genre: 'Mixte', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Oud nude', description: 'Connu pour sa noirceur et sa sophistication, le bois de oud se met à nu au contact d’une amande blanche. En cœur, un accord framboise troublant comme l’empreinte d’un baiser rehausse la blondeur du somptueux cèdre Atlas. Bois à fleur de peau, les pétales d’une rose charnelle effleurent avec sensualité l’écorce de ce bois nude. Illuminé, le bois de oud se dévoile, attendri par l’onctuosité du santal puis exalté par la teinture de vanille de Madagascar. ', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw2e4470df/primary_packshot_3/2022/Fragrance/A&M/Parfums/AM-OUDS_PRIMARY-VISUAL_PDP_NUDE.jpg?sw=900&sh=900', intensity: 4, genre: 'Mixte', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un dessert très gourmand'},
  {name: 'Cherry oud', description: 'Dévoilant ses facettes carmin les plus ravageuses, le bois de oud noir se laque d’une note rouge cerise. Entre le rouge et le noir, une couleur olfactive inédite et puissante qu’exalte un duo de roses au cœur de la fragrance : un absolu de rose turque miellé et une essence de rose bulgare fruitée.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw3bdd432b/primary_packshot_3/2022/Fragrance/A&M/Parfums/AM-OUDS_PRIMARY-VISUAL_PDP_CHERRY.jpg?sw=900&sh=900', intensity: 5, genre: 'Mixte', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un fruit frais ou sucré'},
  {name: 'Aqua allegoria orange soleia', description: 'Orange soleia est un voyage extraordinaire à travers les jardins d’oranger de sicile. c’est une création ensoleillée et survitaminée autour de l’orange sanguine.', brand: 'Guerlain', price: 139, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw25621883/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_ORANGE_SOLEIA_EDT_125ML_-_FORMAT_WEB.png?sw=900&sh=900', intensity: 1, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un cocktail intense et puissant'},
  {name: 'Aqua allegoria bergamote calabria', description: 'Bergamote calabria, c’est un voyage ensoleillé au cœur de la bergamote zestée fleurie et fruitée inspirée de la beauté des plantations du sud de l’italie en calabre.', brand: 'Guerlain', price: 101, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwdc69221b/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Parfums/Key_Visuals/AA_SECONDARY-VISUAL_PDP_BERGAMOTE.jpg?sw=900&sh=900', intensity: 3, genre: 'Mixte', period: 'Soirée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Aqua allegoria flora salvaggia', description: 'Flora salvaggia, c’est le souffle de liberté d’une étendue de fleurs sauvages.', brand: 'Guerlain', price: 101, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwd50f8d95/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_FLORA_SALVAGGIA_EDT_125ML_-_FORMAT_WEB.png?sw=900&sh=900', intensity: 2, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un bouquet de fleurs'},
  {name: 'Aqua allegoria flora cherrysia', description: 'Flora cherrysia s’inspire du japon au moment de hanami afin de créer un parfum plein de poésie, à l’image des cerisiers en fleurs.', brand: 'Guerlain', price: 139, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw8971f769/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_FLORA_CHERRYSIA_EDT_125ML_-_FORMAT_WEB.png?sw=900&sh=900', intensity: 2, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Aqua allegoria nettare di sole ', description: 'Comme si les abeilles n’avaient pollinisé que les plus grandes fleurs de la parfumerie : magnolia, rose, jasmin sambac. Un accord de miel de beauté glacé par une note aquatique s’exprime comme une ardente caresse du soleil sur la peau.', brand: 'Guerlain', price: 139, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwaca702c1/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_NETTARE_DI_SOLE_EDT_125ML_-_FORMAT_WEB_.png?sw=700&sh=700', intensity: 1, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Des embruns rafraichissants'},
  {name: 'Aqua allegoria nerolia vetivier', description: 'L’éclatitude floral du néroli de Calabre, souligné de vétiver et rafraîchi par le basilic, associé à un délicieux accord figue.', brand: 'Guerlain', price: 101, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw4e7765ba/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Parfums/Key_Visuals/AA_SECONDARY-VISUAL_PDP_NEROLI.jpg?sw=700&sh=700', intensity: 2, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Aqua allegoria forte rosa rossa forte', description: 'Rosa Rossa Forte, une éclosion majestueuse de roses suaves baignées de lumière, associées à une pêche blanche juteuse sur un fond délicieusement boisé.', brand: 'Guerlain', price: 116, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw92bf3aa5/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Forte/AA-FORTE_SECONDARY-VISUAL_PDP_01-ROSSA.jpg?sw=700&sh=700', intensity: 3, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un fruit frais ou sucré'},
  {name: 'Aqua allegoria forte mandarine basilic', description: 'Mandarine Basilic Forte, une mandarine dorée associée à un basilic vibrant et sublimée par la chaleur du bois de santal et la délicieuse teinture de vanille.', brand: 'Guerlain', price: 116, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwba873235/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Forte/AA-FORTE_SECONDARY-VISUAL_PDP_01-MANDARINE.jpg?sw=900&sh=900', intensity: 4, genre: 'Mixte', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Aqua allegoria herba fresca', description: 'Herba fresca, c’est une promenade champêtre tonique et rafraîchissante dans les herbes mouillées de rosée.', brand: 'Guerlain', price: 139, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw28f931f3/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_HERBA_FRESCA_EDT_125ML_-_FORMAT_WEB.png?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'Aqua allegoria pera granita', description: 'Pera granita, c’est la saveur d’un granité désaltérant à l’ombre des poiriers dans un jardin méditerranéen.', brand: 'Guerlain', price: 139, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw5f9caa02/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_PERA_GRANITA_EDT_125ML_-_FORMAT_WEB_.png?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Aqua allegoria pamplelune', description: 'C’est un jardin imaginaire composé de citrus menés par le pamplemousse. une pointe de cassis lui donne une envolée fruitée qui signe la fragrance.', brand: 'Guerlain', price: 139, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwae7d5397/primary_packshot_3/2022/Fragrance/Aqua_Allegoria/Revamp%20Packshot/AQUA_ALLEGORIA_PAMPLELUNE_EDT_125ML_-_FORMAT_WEB.png?sw=900&sh=900', intensity: 1, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Mon guerlain', description: 'Mon Guerlain Eau de Parfum est une fragrance ambrée sublimée des matières premières d’exception : la lavande française, le jasmin sambac, le santal et la vanille tahitensis. Elle exprime la quintessence d’une histoire riche d’expériences, de savoir-faire et de générosité distillée avec la même passion depuis 1828.', brand: 'Guerlain', price: 113, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwc77ad64f/primary_packshot_3/2022/Fragrance/Mon_Guerlain/G013139_3346470131392_MON-G-17-EDP-50ML-SPR.png?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Shalimar', description: 'Parfum mythique de la maison Guerlain, Shalimar est un sillage éternel à la sensualité obsédante et au flacon iconique, symbole d’une histoire d’amour légendaire et incandescente. Le premier ambré de la parfumerie incarne une féminité enivrante marquée d’un soupçon d’interdit.', brand: 'Guerlain', price: 113, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw3ca1c221/Secondary_visuals_2/2021/Shalimar/SHALIMAR__SECONDARY-VISUAL_PRODUCT-PAGE_EDP.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Shalimar souffle de parfum', description: 'Souffle de Parfum est une caresse parfumée. Une eau de parfum éclatitudeante, où les notes pétillantes d’agrumes se mêlent à la splendeur d’un bouquet de jasmin, enveloppé de sensuels muscs blancs et d’une vanille addictive. Une réinterprétation florale du mythique Shalimar.', brand: 'Guerlain', price: 150, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwa1e4a222/primary_packshot_3/2022/Fragrance/Shalimar/G011666_3346470116665_SHAL-14-SOUFFLE-EDP-90ML.png?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Mitsouko', description: 'Mitsouko… Ce prénom qui, en japonais signifie mystère, est celui de l’héroïne du roman La Bataille, de Claude Farrère. Prise entre le serment qui la lie à son époux, le jeune marquis Yorisaka, et son amour secret pour un officier de la marine anglaise, Mitsouko lutte avec noblesse contre les élans de son coeur. Inspiré par cette femme, Jacques Guerlain imagine ce chypré à la fois subtilement androgyne et follement féminin. Le parfumeur lui offre une incroyable modernité en associant pour la première fois une pêche fruitée, veloutée et épicée aux senteurs boisées du patchouli. Une combinaison audacieuse à la saveur de fruit défendu qui a fait de Mitsouko un parfum précurseur et avant-gardiste, et le symbole d’une féminité forte qui ose révéler sa part de masculinité.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw7bd0771d/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G024104_3346470241046_MITS-97-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Jardins de Bagatelle', description: 'Séduire, mais aussi se plaire à soi et -surtout !- se faire plaisir. Faire de sa vie une symphonie joyeuse et entraînante. Telle est la philosophie de cette hédoniste spontanée et épanouie. Pour créer le parfum de cette femme libre et indépendante, Jean-Paul Guerlain s’est inspiré d’un défi : celui de Marie-Antoinette au comte d’Artois, de lui construire le château de Bagatelle en moins de 64 jours. Décrits comme une « folie », ses jardins sont devenus un symbole du romantisme. De cet îlot de paradis a surgi un bouquet d’amour pétillant et lumineux de néroli, de roses et de fleurs blanches, transpercé d’une tubéreuse envoûtante. Une bagatelle follement séductrice et empreinte de joie de vivre.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwd18a3518/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014309_3346470143098_JDB-21-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Idylle', description: 'L’amour lui donne des ailes. De coups de cœur en coups de folie, elle s’enflamme avec bonheur, plongitudee avec délice dans les jeux des sentiments. Pour incarner cette incorrigible romantique, le parfumeur Thierry Wasser a imaginé une palette rose, plus exactement celle de la « communelle de roses bulgares », une spécificité Guerlain. Sortant en majesté d’un bouquet frais et joyeux de lilas, pivoine, d’un accord muguet et de freesia, elle est associée à la sensualité de notes chyprées, ciselées de patchouli et de muscs blancs. Dans l’accord parfait de cette délicate Idylle se dessine le tourbillon de l’amour exubérant et pétillant, la sensation d’une émotion inoubliable.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwf885d10f/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014320_3346470143203_IDYL-21-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Des embruns rafraichissants'},
  {name: 'Champ-Elysees', description: 'Une promenade sur la plus belle avenue du monde, sous le soleil d’une fin d’après-midi. Deux regards qui se croisent, un éclatitude de rire et l’envie de s’échapper pour quelques heures impromptues. Cette vie menée tambour battant, ouverte à l’improvisation, s’illumine du sillage de Champs-Élysées. Hommage à l’adresse mythique de Guerlain, il incarne le rayonnement d’une ville en perpétuel mouvement, le lieu de toutes les rencontres et l’envie d’une femme libre de faire de sa vie un jeu. Sous la transparence d’une rose jaillit le jaune du mimosa, lumineux comme jamais. Arrondie de la douceur du bois d’amandier, Champs-Élysées est une lumière dansante, une caresse souriante sur la peau.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwdaebb3bc/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014321_3346470143210_C-EL-21-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Des embruns rafraichissants'},
  {name: 'Insolence', description: 'Spontanée, parfois excessive et toujours sûre d’elle, elle avance avec la grâce désinvolte et l’élégance ironique des conquérantes. Insolence brosse le portrait d’une femme à la sensualité audacieuse, à qui il est impossible de résister. À la fois floral, fruité et poudré, il signe le parfum d’une séduction gorgée d’impertinence. Sur-dosé comme jamais, presque survolté, l’accord violette entraîne dans son sillage la gourmandise de la fraise des bois, la volupté de l’iris et l’éclatitude de la fleur d’oranger. Insolence résonne comme une ode à une femme rayonnante, libre et surprenante qui lance le défi d’un amour sans imite : « qui m’aime me suive ! ».', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw1f5fc1dc/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014323_3346470143234_INSO-21-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un fruit frais ou sucré'},
  {name: 'Liu', description: 'Jusqu’où irait-on par amour ? Passionné d’opéra, Jacques Guerlain trouve la réponse à cette question ultime dans le lyrisme de l’opéra Turandot, de Puccini et de Liu, l’une des héroïnes de cette histoire d’amour. En dessinant son portrait olfactif, le parfumeur rend hommage à une femme prête à tous les sacrifices pour l’homme qu’elle aime, et imagine la légende d’un amour rare, inconditionnel. Dans ce floral aldéhydé, les envolées de jasmin et de rose chantent l’air d’une sensualité charnelle, vibrante d’iris et de vanille sur fond de notes boisées. Le parfum voluptueux d’une amoureuse de l’ombre.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwa8a35b61/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014325_3346470143258_LIU-21-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'L’initial', description: 'L’adrénaline, le frisson de la découverte la font rosir de plaisir… À l’aube de sa vie de femme, encore innocente mais déjà audacieuse, elle s’apprête à plongitudeer dans un nouveau mystère, celui des pouvoirs de la féminité. Dans cette aventure, un parfum la suit : L’Initial, une fragrance qui suggère l’entrée dans un nouveau monde ; le passage à l’âge adulte. C’est pour sa jeune nièce que Thierry Wasser a composé ce floral ambré lumineux en s’inspirant de l’inoubliable Shalimar. Sous une pluie d’agrumes et de jasmin éclot un cœur de rose et d’iris pallida, caressés de vanille : dans la fraîcheur d’une sensualité à peine esquissée, L’Initial écrit la légende d’une jeune fille rêvant à son premier amour.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw55318481/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014326_3346470143265_LINITIAL-21-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Jicky', description: 'Elle sème le trouble sur son passage et parfois même provoque avec malice, jouant de l’ambiguïté de ses courbes androgynes. Dans l’ombre de sa silhouette, le souvenir de Jicky, une femme dont Aimé Guerlain tomba amoureux lors de ses études en Angleterre. Le parfumeur rendra hommage à cet amour de jeunesse avec un sillage si révolutionnaire qu’il fut qualifié de premier parfum moderne. Jicky brise les frontières du masculin-féminin et surprend par la radicalité de ses contrastes. Quand sa lavande citronnée et son accord de fougère soufflent le froid, ses notes boisées et vanillées apportent chaleur et caractère. S’il dérouta d’abord les femmes autant qu’il séduisit les hommes, avant d’être adopté par tous, Jicky demeure à jamais « de l’émotion offerte dans un flacon ».', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwb984854c/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014315_3346470143159_JICKY-20-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un bouquet de fleurs'},
  {name: 'Nahema', description: 'Son tempérament de feu la rend insaisissable et… follement attirante, à l’image de Nahema, princesse de l’un des contes des Mille et Une Nuits, mais aussi de Catherine Deneuve dans le film Benjamin ou les Mémoires d’un puceau (Michel Deville, 1968). L’interprétation de l’actrice a tant bouleversé Jean-Paul Guerlain qu’il en a conçu un parfum. Troublant et énigmatique, cet élixir ambré à la fois fleuri et fruité resta, à l’image des femmes qui l’inspirèrent, longitudetemps indomptable pour le parfumeur. Quatre ans de travail et plus de cinq cents essais furent nécessaires pour cueillir cette rose absolue et veloutée, gorgée d’un accord pêche et enrobée de patchouli et de santal. Le symbole enivrant d’un amour si brûlant qu’il peut consumer celui qui s’en approche.', brand: 'Guerlain', price: 146, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw540c01ce/primary_packshot_3/2022/Fragrance/Les%20L%C3%A9gendaires/G014311_3346470143111_NAHE-20-EDP-75ML-SPR.png?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Musc Noble', description: 'La profondeur du musc se marie à une rose majestueuse et à une note vibrante de cèdre. Tour à tour puissant, chaud et poudré, le musc sublime la fragrance dans un accord intense et plein de caractère.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw0418e12e/primary_packshot_3/2022/Fragrance/Absolus_Dorient/G013507_3346470135079_MUSC_NOB-22-EDP-VAPO-125ML.png?sw=900&sh=900', intensity: 5, genre: 'Pour homme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un cocktail intense et puissant'},
  {name: 'Oud essentiel', description: 'À la fois douce et puissante, cette fragrance boisée cuirée mêle dans une subtile alchimie, les notes suaves de rose que viennent troubler les mystérieuses notes de cuir et d‘encens. Une empreinte olfactive unique à mi-chemin entre Orient et Occident.', brand: 'Guerlain', price: 179, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw15f6bce4/primary_packshot_3/2022/Fragrance/Absolus_Dorient/Key_Visuals/AO_SECONDARY-VISUAL_PRODUCT-PAGE_OUD-01.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un cocktail intense et puissant'},
  {name: 'Musc outreblanc', description: 'Sculpter le musc comme on sculpte le marbre, c’est la démarche créative que les Parfumeurs Guerlain ont suivie pour imaginer un parfum autour du musc. De la matière brute émerge la forme la plus délicate, une sculpture olfactive à l’image du Baiser d’Auguste Rodin qui fait surgir d’un bloc de marbre un amour à fleur de peau.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw17613a54/Secondary_visuals_2/2021/A&M/ARMA-MUSC_SECONDARY-VISUAL_PRODUCT-PAGE.jpg?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un cocktail intense et puissant'},
  {name: 'Cuir beluga', description: 'La note daim blanc de Cuir Beluga rappelle le travail de Jean-Michel Frank. Dans les années 30, Jacques Guerlain fait appel à ce jeune décorateur et architecte, pour sublimer la boutique du 68, avenue des Champs-Elysées où il dessinera un mobilier gainé de daim blanc d’un modernité extrême.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw4391f1f1/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_CUIR-BELUGA.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un jus d’agrumes vitaminé'},
  {name: 'Iris torrefie', description: 'Évoquant l’élégance à la parisienne si chère à Guerlain, Iris Torréfié est un plongitudeeon olfactif dans les cafés littéraires mythiques de Saint-Germain-des-Prés. Le Café de Flore ou les Deux Magots sont toujours des lieux de prédilection pour les artistes de la capitale française.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw42f16609/primary_packshot_3/2021/A&M/Face/201130_TLE_GUERLAIN_PARFUM_100ML_IRIS_TORREIFIE_S.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Un souvenir de vacances épicé'},
  {name: 'Spiritueuse double vanille', description: 'Oser le surdosage de vanille et l’enivrer de rhum liquoreux et de bois de cèdre.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwceaca7ae/Secondary_visuals_2/2021/A&M/ARMA-VANILLE_SECONDARY-VISUAL_PRODUCT-PAGE.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un cocktail intense et puissant'},
  {name: 'Angelique noire', description: 'Mi-ange, mi-démon, l’amertume verte, croquante et végétale de l’angélique est maîtrisée par la douceur enveloppante de la vanille.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw81b6ac9c/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_ANGELIQUE-NOIRE.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'Rose barbare', description: 'La rose s’affirme pour mieux renverser. D’un rose sombre, flamboyant comme une goutte de sang, dotée d’épines piquantes et d’un tempérament insensé, la rose n’a jamais été aussi téméraire.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw9cb859b6/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_ROSE-BARBARE.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Des embruns rafraichissants'},
  {name: 'La petite robe noire intense', description: 'Inspirée par le style inimitable des Parisiennes, La Petite Robe Noire est un hymne à la liberté et à l’amour, une incarnation de l’élégance et de l’allure, une invitation à la joie de vivre et à l’irrévérence.', brand: 'Guerlain', price: 117, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwb825da97/Secondary_visuals_2/2022/Fragrance/LPRN/EDPI/LPRN_SECONDARY-VISUAL_PDP_01.jpg?sw=900&sh=900', intensity: 4, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un fruit frais ou sucré'},
  {name: 'La petite robe noire absolue', description: 'Le sillage floral fruité intense de l’Eau de Parfum Absolue est un hommage vibrant à la rose. La puissance d’une eau de parfum intense, la sophistication d’un absolu de parfum, et une rose brodée des accents boisés du patchouli qui habillent la peau de notes intenses et élégantes.', brand: 'Guerlain', price: 117, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwcc985527/Secondary_visuals_2/2023/Fragrances/LPRN/LPRN-ABSOLUE_SECONDARY-VISUAL_PDP_03.jpg?sw=700&sh=700', intensity: 3, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un fruit frais ou sucré'},
  {name: 'Santal pao rosa', description: 'La Nature devient Art lorsque la force du santal s’enveloppe de tendres pétales de rose. Entre bois et fleur, une partition des contraires renforcée par une entrée fraiche et épicée de cardamome, et un fond plus sombre d’oud et de notes de myrrhe.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw8f9c6fc0/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_SANTAL-PAO-ROSA.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un déjeuner entre amis', smell: 'Une balade en forêt'},
  {name: 'Bois d’armenie', description: 'S’inspirant de la tradition arménienne invitant à brûler le benjoin pour former des volutes d’encens, le Parfumeur Guerlain réinterprète l’odeur du papier d’Arménie, en le dotant d’accents vanillés addictifs et chaleureux.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwe84fcd19/primary_packshot_3/2021/A&M/Face/201130_TLE_GUERLAIN_PARFUM_100ML_BOIS_D_ARMENIE_S.jpg?sw=900&sh=900', intensity: 5, genre: 'Pour femme', period: 'Soirée', season: 'Plutôt l’hiver', situations: 'Un moment cocooning', smell: 'Un souvenir de vacances épicé'},
  {name: 'Cruel Gardenia', description: 'Cruel Gardénia est un piège de délicatesse. Habituellement envoûtante et presque narcotique, la fleur se découvre renversante de douceur.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw1967b0ea/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_CRUEL-GARDENIA.jpg?sw=900&sh=900', intensity: 4, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Des embruns rafraichissants'},
  {name: 'Néroli Outrenoir', description: 'Néroli ou la blancheur fusante et Outrenoir, son opposé. Tel un éclatitude dans l’obscurité, l’essence de Néroli, éclairée par la bergamote et le petit grain, affonte des notes plus ténébreuses et énigmatiques de thé fumé.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw4389fec3/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_NEROLI.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un week-end intense', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'Joyeuse tubereuse', description: 'Comme cueillie en plein champ, l’absolu tubéreuse révèle une fleur étonnamment fraîche, encore gorgée de sève grâce à une profusion de notes vertes en tête. Jamais elle n’a été si joyeuse, subtilement escortée par un sillage sensuel tissé de vétiver, santal et ambrette.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwd65c0e39/primary_packshot_3/2021/A&M/Face/211013_GUERLAIN_AM_50ML_JOYEUSE_TUBEREUSE_G.jpg?sw=700&sh=700', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'Rose cherie', description: 'Déclaration d’amour signée Guerlain, Rose Chérie rend hommage à la fleur chérie des Parfumeurs. Réhaussé d’une note d’amande, son sillage révèle une délicate rose au coeur qui bat.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw559da8fb/Secondary_visuals_2/2021/A&M/AM_SECONDARY-VISUAL_PRODUCT-PAGE_ROSE-CHERIE.jpg?sw=900&sh=900', intensity: 4, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Des embruns rafraichissants'},
  {name: 'Epice Volees', description: 'Épices Volées est une composition à double visage. Il séduit autant par la fraîcheur de la bergamote et du citron que par l’impertinence de ses notes épicées. En fond le patchouli sulfureux rencontre l’élégance réconfortante du santal.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dw1a052cd7/primary_packshot_3/2021/A&M/Face/201130_TLE_GUERLAIN_PARFUM_100ML_EPICES_VOLEES_S.jpg?sw=900&sh=900', intensity: 3, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’hiver', situations: 'Un week-end intense', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'frenchy lavande', description: 'Frenchy Lavande joue la dualité pour mieux stupéfier: des notes hespéridées de verveine, accentuées de bergamote, citron et petit grain, mettent en tension la lavande. Sur fond de vétiver, élégance oblige.', brand: 'Guerlain', price: 325, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwf1383ccb/primary_packshot_3/2021/A&M/Face/201130_TLE_GUERLAIN_PARFUM_100ML_FRENCHY_LAVANDE_S.jpg?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un bouquet d’herbes et aromates'},
  {name: 'Mon Guerlain Sparkling bouquet', description: 'Mon Guerlain Sparkling Bouquet c’est l’empreinte olfactive d’une personnalité radieuse. Une fragrance facettée comme un joyau, qui rejoue dans un registre fruité et intensément lumineux les ingrédients essentiels de Mon Guerlain. L’incontournable duo lavande-vanille est sublimé d’une note poire pétillante et d’un jasmin sambac lumineux. Un sillage ambré frais fruité captivant au charme magnétique.', brand: 'Guerlain', price: 157, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwcedf843d/primary_packshot_3/2022/Fragrance/Mon_Guerlain/G014247_3346470142473_MON-G-21-SPARKLING-EDP-100ML-SPR.png?sw=700&sh=700', intensity: 4, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un déjeuner entre amis', smell: 'Un fruit frais ou sucré'},
  {name: 'Terracotta le parfum', description: 'Thierry Wasser, Maître-Parfumeur Guerlain, a interprété la mythique poudre Terracotta dans un parfum gorgé de soleil. Une fragrance lumineuse, inspirée par l’univers rayonnant de Terracotta. Un départ immédiat pour un ailleurs exotique et paradisiaque.', brand: 'Guerlain', price: 106, photo: 'https://www.guerlain.com/dw/image/v2/BDCZ_PRD/on/demandware.static/-/Sites-GSA_master_catalog/default/dwa3711f6a/images/G041769/3346470417694_G041769_TERRA%2014%2030%20ANS%20PARFUM%20EDT%20100ML_NA_a_1.png?sw=900&sh=900', intensity: 2, genre: 'Pour femme', period: 'Journée', season: 'Plutôt l’été', situations: 'Un moment cocooning', smell: 'Un bouquet de fleurs'}
])
puts "attached photos"
perfumes.each_with_index do |perfume, index|
  # Chemins possibles pour les fichiers avec les deux extensions
  png_path = "app/assets/images/perfumesperfumes#{index}.png"
  jpeg_path = "app/assets/images/perfumesperfumes#{index}.jpg"
  # Vérifier quelle extension de fichier existe
  file_path = if File.exist?(png_path)
                png_path
              elsif File.exist?(jpeg_path)
                jpeg_path
              else
                nil
              end
  if file_path
    file = File.open(file_path, "rb")
    puts "On attache l'image"
    perfume.illustration.attach(io: file, filename: "#{perfume.name}#{File.extname(file_path)}", content_type: "image/#{File.extname(file_path).delete('.')}")
    perfume.save!
    file.close # Assurez-vous de fermer le fichier après utilisation
  else
    puts "Aucun fichier trouvé pour #{perfume.name} à l'index #{index}"
  end
end
puts "finished creating perfumes"
puts "Creating results..."
results = Result.create!([
  { user: users.first, name: 'Resultat 1', description: 'Premier résultat', answer_1: 'A un proche', answer_2: 'Pour femme', answer_3: 'Ne passe pas inaperçu', answer_4: 'Journée', answer_5: 'Plutôt l’été', answer_6: 'Réponse 6', answer_7: 'Un déjeuner entre amis', answer_8: 'Un jus d’agrumes vitaminé,Un bouquet d’herbes et aromates', answer_9: 'reponse 9', answer_10: 'Réponse 10' },
  { user: users.last, name: 'Resultat 2', description: 'Deuxième résultat', answer_1: 'A vous même', answer_2: 'Pour homme', answer_3: 'Est plutôt intime, juste pour vous', answer_4: 'Tout le temps', answer_5: 'Plutôt l’été', answer_6: 'Réponse 6', answer_7: 'Toute occasion', answer_8: 'Un jus d’agrumes vitaminé,Un bouquet d’herbes et aromates', answer_9: 'Un jus d’agrumes vitaminé, Un bouquet d’herbes et aromates', answer_10: 'Réponse 10' },
  { user: users.last, name: 'Resultat 3', description: 'Troisième résultat', answer_1: 'A vous même', answer_2: 'Mixte', answer_3: 'Ne passe pas inaperçu', answer_4: 'Tout le temps', answer_5: 'Plutôt l’hiver', answer_6: 'Réponse 6', answer_7: 'Un week-end intense', answer_8: 'Un fruit frais ou sucré,Un bouquet d’herbes et aromates', answer_9: 'Reponse 9', answer_10: 'Réponse 10' }
])

puts "finished creating results"
puts "creating perfume results..."
PerfumeResult.create!([
  { perfume: perfumes[0], result: results[0] },
  { perfume: perfumes[1], result: results[1] }
])
puts "finished creating perfume results"
puts "creating notes..."
# notes = Note.create!([
#   { perfume: perfumes[0], tete: 'Bergamote', coeur: 'Iris', fond: 'Vanille' },
#   { perfume: perfumes[1], tete: 'Lavande', coeur: 'Jasmin Sambac', fond: 'Bois de santal' },
#   { perfume: perfumes[2], tete: 'Mandarine', coeur: 'Basilic', fond: 'Thé vert' },
#   { perfume: perfumes[3], tete: 'Amande', coeur: 'Cuir', fond: 'Vanille' }
# ])
notes_data = [
  {tete: 'Menthe, Bergamote', coeur: 'Romarin, Cardamome, Coriandre, Cerise, Amande', fond: 'Patchouli, Vanille, Fève de tonka, Réglisse' },
  {tete: 'Bergamote, Amande, Baie rose', coeur: 'Héliotrope, Cannelle, Prune', fond: 'Cuir, Tabac, Patchouli, Cèdre' },
  {tete: 'Piment', coeur: 'Fève de tonka', fond: 'Encens' },
  {tete: 'Lavande, Romarin, Bergamote, Thym', coeur: 'Cerise', fond: 'Vanille, Bois de santal, Cuir, Fève de tonka, Amande' },
  {tete: 'Bergamote, Citron, Orange, Néroli', coeur: 'Patchouli, Jasmin, Lavande', fond: 'Bois de santal, Mousse de chêne' },
  {tete: 'Orange, Verveine, Bergamote', coeur: 'Néroli, Citron, Orange', fond: 'Romarin, Cèdre, Fève de tonka' },
  {tete: 'Orange', coeur: 'Fleur d’oranger, Menthe', fond: 'Romarin, Lavande' },
  {tete: 'Encens', coeur: 'Citron', fond: 'Ambre gris' },
  {tete: 'Figue, Poivre noir, Poivre rose', coeur: 'Cèdre, Rose, Patchouli', fond: 'Musc, Cuir' },
  {tete: 'Osmanthus, Ylang-Ylang', coeur: 'Cuir, Musc', fond: 'Cèdre, Santal, Tabac' },
  {tete: 'Lavande, Néroli, Orange, Citron', coeur: 'Rose, Jasmin', fond: 'Cannelle, Patchouli, Vanille, Bouleau, Girofle, Fève de tonka, Cèdre, Ambre gris' },
  {tete: 'Bergamote, Tabac, Citron, Noix de muscade, Néroli, Mandarine', coeur: 'Vetiver, Poivre noir, Sauge, Bois de santal', fond: 'Vetiver, Mousse de chêne, Cuir, Myrrhe, Civette, Ambre, Fève de tonka' },
  {tete: 'Badiane de chine, Bergamote, Citron, Poivre noir', coeur: 'Cacao, Bois de santal, Encens, The, Jasmin', fond: 'Patchouli' },
  {tete: 'Bergamote ', coeur: 'Rose, Prune, Framboise', fond: 'Cannelle, Patchouli, Vanille, Santal, Cuir, Oud, Caramel' },
  {tete: 'Cardamome, Angelique, Poivre rose', coeur: 'Poivre noir, Cafe', fond: 'Bois de santal, Oud, Patchouli' },
  {tete: 'Cacao, Rose', coeur: 'Rhum, Epices', fond: 'The lapsang souchong' },
  {tete: 'Citron', coeur: 'Cuir, Praline', fond: 'Oud' },
  {tete: 'Amande, Oud', coeur: 'Framboise, Cèdre d’atlas', fond: 'Bois de santal, Vanille' },
  {tete: 'Cerise', coeur: 'Rose de Turquie, Rose de Bulgarie', fond: 'Oud, Cuir' },
  {tete: 'Poivre rose, Orange, Bergamote', coeur: 'Petit-grain, Menthe', fond: 'Musc, Fève de tonka' },
  {tete: 'Bergamote', coeur: 'Gingembre, Cardamome', fond: 'Petit-grain' },
  {tete: 'Violette, Melon, Fleurs sauvages', coeur: 'Jasmin, Fleur d’oranger', fond: 'Violette, Musc blanc, Iris' },
  {tete: 'Bergamote', coeur: 'Fleur de cerisier, Poire, Rose', fond: 'Violette, Musc' },
  {tete: 'Fleur d’oranger, Bergamote', coeur: 'Rose, Magnolia, Jasmin', fond: 'Miel' },
  {tete: 'Bergamote, Feuille de figuier, Petit-grain', coeur: 'Néroli, Figue, Rose', fond: 'Vetiver, Cèdre, Fève de tonka' },
  {tete: 'Peche, Bourgeon de cassis, Poivre noir, Amande', coeur: 'Rose de Bulgarie, Rose de Damas', fond: 'Benjoin, Patchouli, Bois de santal' },
  {tete: 'Mandarine, Basilic, Bourgeon de cassis', coeur: 'Fleur d’oranger, Miel, Anis, Rose de Bulgarie', fond: 'Vanille, Bois de santal' },
  {tete: 'Menthe, Citron', coeur: 'Muguet, Cyclamen, The', fond: 'Fleur d’oranger' },
  {tete: 'Pamplemousse, Bergamote, Citron', coeur: 'Osmanthus, Hedione, Poire', fond: 'Musc Blanc, Cèdre, Mousse de chêne' },
  {tete: 'Pamplemousse, Bergamote, Citron, Petit-grain', coeur: 'Néroli, Cassis', fond: 'Patchouli, Vanille' },
  {tete: 'Bergamote, Mandarine, Poire', coeur: 'Néroli, Jasmin, Lavande', fond: 'Iris, Vanille, Bois de santal' },
  {tete: 'Bergamote, Citron', coeur: 'Rose, Jasmin', fond: 'Patchouli, Vanille, Iris, Fève de tonka' },
  {tete: 'Mandarine, Bergamote, Citron', coeur: 'Citron, Fleur d’oranger, Jasmin', fond: 'Vanille, Musc blanc' },
  {tete: 'Mandarine, Bergamote, Citron', coeur: 'Rose, Peche, Néroli, Jasmin', fond: 'Mousse de chêne, Vetiver, Patchouli, Vanille, Girofle' },
  {tete: 'Bergamote, Violette, Citron', coeur: 'Iris, Cassis, Narcisse, Muguet', fond: 'Vetiver, Patchouli, Civette, Cèdre' },
  {tete: 'Muguet, Pivoine, Freesia, Lys blanc', coeur: 'Rose de Bulgarie, Jasmin', fond: 'Musc blanc, Patchouli' },
  {tete: 'Mimosa, Rose', coeur: 'Mimosa, Buddleia, Bourgeon de cassis', fond: 'Amande, Vanille, Hibiscus' },
  {tete: 'Framboise', coeur: 'Rose, Fleur d’oranger, Violette', fond: 'Vanille, Iris, Fève de tonka' },
  {tete: 'Citron', coeur: 'Rose, Jasmin', fond: 'Vanille, Iris' },
  {tete: 'Orange, Bergamote, Jasmin', coeur: 'Iris, Rose de Turquie', fond: 'Vanille, Caramel, Fève de tonka, Amande, Patchouli' },
  {tete: 'Lavande, Romarin, Bergamote', coeur: 'Rose, Jasmin, Bois de rose', fond: 'Coumarine, Civette, Fève de tonka, Vanille' },
  {tete: 'Mandarine, Bergamote', coeur: 'Rose, Peche', fond: 'Benjoin, Vetiver, Vanille, Santal, Iris, Fève de tonka' },
  {tete: 'Baie rose, Safran, Geranium', coeur: 'Rose, Musc', fond: 'Ciste, Cèdre, Ambre' },
  {tete: 'Safran, Oud', coeur: 'Rose, Cèdre', fond: 'Bois de gaiac, Cuir, Encens' },
  {tete: 'Musc blanc, Néroli, Ambrette', coeur: 'Iris, Fleur d’oranger, Rose de Bulgarie', fond: 'Lait, Bois de santal, Ambre blanche' },
  {tete: 'Mandarine', coeur: 'Patchouli, Immortelle', fond: 'Vanille, Héliotrope, Daim, Ambre' },
  {tete: 'Cardamome, Cafe, Bergamote', coeur: 'Iris, Ambrette', fond: 'Cuir, The, Vanille, Ambre' },
  {tete: 'Baie rose, Bergamote, Encens', coeur: 'Rose, Jasmin, Ylang-Ylang', fond: 'Vanille, Benjoin, Rhum' },
  {tete: 'Angelique, Poire, Poivre rose', coeur: 'Jasmin, Carvi', fond: 'Vanille, Angelique, Cèdre' },
  {tete: 'Rose', coeur: 'Rose', fond: 'Peche, Patchouli' },
  {tete: 'Myrtille, Bergamote, Framboise', coeur: 'Rose, Fleur d’oranger', fond: 'Vanille, Musc blanc, Patchouli, Bois de santal' },
  {tete: 'Cerise, Amande, Bergamote', coeur: 'Rose, The, Iris', fond: 'Cuir, Patchouli, Fève de tonka' },
  {tete: 'Bois de santal, Cardamome', coeur: 'Figue', fond: 'Oud, Myrrhe' },
  {tete: 'Encens,Iris, Poivre rose', coeur: 'Benjoin, Bois de gaiac, Coriandre', fond: 'Copaiba, Patchouli, Musc blanc' },
  {tete: 'Néroli, Rose, Peche', coeur: 'Gardenia, Violette, Ylang-Ylang', fond: 'Musc, Fève de tonka, Bois de santal, Vanille' },
  {tete: 'Petit-grain, Bergamote', coeur: 'Fleur d’oranger,Néroli, The', fond: 'Ambrette, Mousse d’arbre, Myrrhe' },
  {tete: 'Herbe', coeur: 'Tubereuse, Lys, Jasmin', fond: 'Vanille, Bois de santal, Vetiver' },
  {tete: 'Rose, Rose de Bulgarie', coeur: 'Violette, Héliotrope', fond: 'Musc, Fève de tonka, Bois de santal, Vanille' },
  {tete: 'Coriandre, Armoise, Citron, Bergamote', coeur: 'Clou de girofle, Cardamome, Sauge, Rose de Bulgarie', fond: 'Bois de santal, Patchouli, Benjoin, Ciste' },
  {tete: 'Verveine, Citron, Bergamote', coeur: 'Petit-grain, Lavande, Cedrat, Sauge, Néroli', fond: 'Vetiver, Ambre gris, Fève de tonka' },
  {tete: 'Poire, Bergamote, Mandarine', coeur: 'Lavande, Pivoine, Jasmin sambac', fond: 'Vanille, Musc blanc, Bois de santal' },
  {tete: 'Fleur de tiare, Noix de coco, Bergamote', coeur: 'Jasmin, Ylang-Ylang, Fleur d’oranger', fond: 'Vanille, Musc' }
]
puts "Ajout des notes"
notes_data.each_with_index do |note_data, index|
  Note.create!(
    perfume: perfumes[index],
    tete: note_data[:tete],
    coeur: note_data[:coeur],
    fond: note_data[:fond]
  )
end
puts "finished creating notes"
puts "creating reviews..."
reviews = Review.create!([
  { user: users.first, perfume: perfumes[0], comment: 'Parfum incroyable!', rating: 5 },
  { user: users.last, perfume: perfumes[1], comment: 'Très frais et agréable.', rating: 4 }
])

comments = [
  'Parfum incroyable!',
  'Très frais et agréable.',
  'Un parfum unique et sophistiqué.',
  'J\'adore ce parfum!',
  'Parfum léger et subtil.',
  'Parfait pour une soirée!',
  'Odeur très agréable.',
  'Ce parfum est mon préféré!'
]

puts "Creating reviews..."
reviews = []

perfumes.each do |perfume|
  rand(1..5).times do
    reviews << {
      user: users.sample,
      perfume: perfume,
      comment: comments.sample,
      rating: rand(3..5)
    }
  end
end
Review.create!(reviews)

puts "finished creating reviews"
puts "creating favorites..."
favorites = Favorite.create!([
  { user: users.first, perfume: perfumes[0] },
  { user: users.last, perfume: perfumes[1] }
])
puts "finished creating favorites"
puts "creating magasins..."
magasins = Magasin.create!([
  { name: 'Guerlain Boutique', address: '68 Avenue des Champs-Élysées, Paris', latitude: 48.8705, longitude: 2.3044, brand: 'Guerlain' },
  { name: 'Sephora - Champs-Élysées', address: '70-72 Avenue des Champs-Élysées, Paris', latitude: 48.8709, longitude: 2.3036, brand: 'Guerlain' },
  { name: 'Galeries Lafayette Haussmann', address: '40 Boulevard Haussmann, Paris', latitude: 48.8738, longitude: 2.3321, brand: 'Guerlain' },
  { name: 'Le Bon Marché Rive Gauche', address: '24 Rue de Sèvres, Paris', latitude: 48.8515, longitude: 2.3264, brand: 'Guerlain' },
  { name: 'Printemps Haussmann', address: '64 Boulevard Haussmann, Paris', latitude: 48.8721, longitude: 2.3282, brand: 'Guerlain' },
  { name: 'Sephora - Saint-Lazare', address: '109 Rue Saint-Lazare, Paris', latitude: 48.8761, longitude: 2.3261, brand: 'Guerlain' },
  { name: 'Marionnaud - Saint-Honoré', address: '1 Rue du Faubourg Saint-Honoré, Paris', latitude: 48.8675, longitude: 2.3241, brand: 'Guerlain' },
  { name: 'Nocibé - Montparnasse', address: '50 Avenue du Maine, Paris', latitude: 48.8421, longitude: 2.3215, brand: 'Guerlain' },
  { name: 'Guerlain Boutique Paris Montaigne', address: '68 Avenue Montaigne, Paris', latitude: 48.8655, longitude: 2.3035, brand: 'Guerlain' },
  { name: 'Guerlain Boutique Saint-Germain', address: '5 Rue de Castiglione, Paris', latitude: 48.8654, longitude: 2.3275, brand: 'Guerlain'},
  { name: 'Guerlain Boutique Vendôme', address: '356 Rue Saint-Honoré, Paris', latitude: 48.8675, longitude: 2.3281, brand: 'Guerlain' },
  ])
  puts "finished creating magasins"
puts "Seed data created successfully!"
